version: '2.4'
services:
  tradefix:
    build: ./dist
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db 
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://db:27020/repair-app
  db:
    image: mongo
    restart: always
    ports:
      - 27020:27017
    volumes:
      - ~/data/repair-app:/data/db
